### ISSUE TITLE
Bower wiredep fails because of bad path at main.

### ISSUE THREAD

**Issue by scaria** [epochjs/epoch#176] opened 2015-06-15 22:06 UTC
The grunt wiredep fails because the main has an absolute path.
```
"main": [
    "/epoch.min.js",
    "/epoch.min.css"
  ],
```

Changing this to

```
"main": [
    "epoch.min.js",
    "epoch.min.css"
  ],
```
works.

**Comment by rsandor** [comment] 2015-10-04 05:16
Seems to be a duplicate of #171

**Comment by rsandor** [comment] 2015-10-04 05:42
Fixed by #168

**Closed by rsandor** 2015-10-04 05:42 UTC
Labels: bug, duplicate
